## Punto 3 Optimizacion

In [10]:
import numpy as np
from scipy.optimize import minimize, Bounds

### Definicion de variables a optimizar
##### Las variables a optimizar en este problema son las probabilidades de cada persona pi, en este caso, 8 personas
### Definicion de funcion objetivo


In [11]:
def funcionObjetivo (X):
    # X entra como un vector
    return np.sum(np.multiply(X,np.log(X)))

Definicion de funciones $T_i$

In [37]:
def T1(i):
    out = 0;
    lista_si = [0,1,5]
    if i in lista_si:
        out = 1;
    else:
        out = 0;
        
    return out

def T2(i):
    out = 0;
    lista_mujeres = [0,3,4]
    if i in lista_mujeres:
        out = 1;
    else:
        out = 0;
        
    return out

def T3(i):
    out = 0
    lista_menosDe10 = [6,7]
    if i in lista_menosDe10:
        out = 1
    else:
        out = 0
        
    return out
    

In [38]:
#Restricciones

def constraint1(P): #Restriccion de igualdad
    X = np.arange(8); #Esto me genera vector de 0 a 7
    suma = 0.35 #Valor de la constante a igualar
    pertenece = np.array([T3(xi) for xi in X])
    for i in range(8):
        suma = suma - pertenece[i]*P[i]
    return suma

def constraint2(P):
    suma = 1 #Valor de la constante a igualar
    for i in range(8):
        suma = suma - P[i]
    return suma

def constraint3(P): #Restriccion de desiguladad
    X = np.arange(8)
    valor_max = 0.3 #El valor del E[T1(X)]<= 0.3
    pertenece = np.array([T1(xi) for xi in X])
    suma = np.sum(np.multiply(pertenece,P))
    return (valor_max-suma)

def constraint4(P):
    X= np.arange(8)
    valor_min = 0.45  #El valor del E[T2(X)]>= 0.45
    pertenece = np.array([T2(xi) for xi in X])
    suma = np.sum(np.multiply(pertenece,P))
    
    return (suma-valor_min);

In [39]:
#Definicion de limites sueprior e inferior

b = [(0.0001,0.9999)]*8

bnds = (b)

#print(bnds)
#bnds = Bounds(bnds)
con1 = {'type': 'eq','fun': constraint1}
con2 = {'type': 'eq','fun': constraint2}
con3 = {'type': 'ineq','fun': constraint3}
con4 = {'type': 'ineq','fun': constraint4}


cons = [con1,con2,con3,con4]

In [40]:
#Definicion de vector solucion inicial
P0 = np.random.rand(8)/10
print(P0)

[0.07448453 0.01261203 0.08561461 0.05510912 0.05280655 0.04762131
 0.02400047 0.0858425 ]


In [41]:
sol = minimize(funcionObjetivo,P0,method='SLSQP',bounds=bnds,constraints=cons)

In [42]:
sol.x

array([0.15001422, 0.06669338, 0.06666782, 0.15000743, 0.14997835,
       0.0666388 , 0.17497623, 0.17502377])

In [43]:
np.sum(sol.x)

1.0

In [44]:
sol.fun

-2.0053532733530797

In [162]:
0.15+0.06+0.06+0.14+0.14+0.06+0.35+0.367

1.327

In [112]:
X = np.arange(11)
print(X)
type(X)
print(X[2])

[ 0  1  2  3  4  5  6  7  8  9 10]
2


In [101]:
P = np.array([T1(xi) for xi in X])
print(P)
np.sum(np.multiply(P,X))

[1 1 0 0 0 1 0 0 0 0 0]


6

In [106]:
funcionObjetivo(X)

C:\Users\LENOVO\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: divide by zero encountered in log
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\LENOVO\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in multiply
  This is separate from the ipykernel package so we can avoid doing imports until


nan

In [52]:
lista_si = [0,1,5]

In [109]:
X2 = np.array([3,4,5,6,7,8])
np.log(X2)

array([1.09861229, 1.38629436, 1.60943791, 1.79175947, 1.94591015,
       2.07944154])

In [54]:
4 in lista_si

False

In [36]:
for i in range(8):
        print(i)

0
1
2
3
4
5
6
7


In [22]:
T = np.matrix([3,4,5,6])

In [48]:
K = np.matrix([1,2,3,4])
np.multiply(K,(T))

matrix([[ 3,  8, 15, 24]])

In [20]:
K=(np.matrix([[3],[3],[3]]))

In [21]:
K.shape

(3, 1)

In [27]:
T.shape

(1, 4)

In [26]:
T = np.transpose(T)

In [29]:
M = np.matrix([[1,2,3],[3,4,5],[6,7,8]])

In [33]:
M2 = np.matrix([[1],[2],[3]])

In [34]:
M2

matrix([[1],
        [2],
        [3]])

In [41]:
print(M2.shape)
print(M.shape)

(3, 1)
(3, 3)


In [42]:
M*M2

matrix([[14],
        [26],
        [44]])

In [43]:
M2*M

ValueError: shapes (3,1) and (3,3) not aligned: 1 (dim 1) != 3 (dim 0)